name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'ubuntu:focal'
      fail-fast: false
    container:
      image: '${{ matrix.image }}'
    env:
      DEBIAN_FRONTEND: noninteractive
      DEBIAN_PRIORITY: critical
      DEBCONF_NOWARNINGS: yes
    steps:
      - name: Build Packages
        run: |
          echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90assumeyes
          echo 'APT::Get::Install-Recommends "false";\nAPT::Get::Install-Suggests "false";' > /etc/apt/apt.conf.d/90norecommends
          apt-get update
          apt-get install gnupg
          apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
          echo 'deb http://repo.aptly.info/ squeeze main' > /etc/apt/sources.list.d/aptly.list
          sed -i 's/^deb \(.*\)$/&\ndeb-src \1/' /etc/apt/sources.list
          apt-get update
          apt-get install build-essential devscripts equivs lsb-release quilt dh-autoreconf lintian aptly
          apt-get source ffmpeg
          cd ffmpeg-*
          sed -i 's/^Build-Depends:$/&\n libsrt-dev (>= 1.4.0),/' debian/control
          sed -i 's/^CONFIG :=.*$/&\n        --enable-libsrt \\/' debian/rules
          mk-build-deps -i -r debian/control
          apt-get clean
          debuild -us -uc -b
          cd ..
          aptly repo create -distribution=$(lsb_release -c -s) default
          aptly repo add default .
          aptly --skip-signing publish repo default
